// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_bicopula_TMBExports
#include <TMB.hpp>
#include "bisurvreg.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "bisurvreg") {
    return bisurvreg(this);
  } else {
    error("Unknown model.");
  }
  return 0;
}
